import prisma from "@/lib/prisma";
import { TodosGrid } from "@/todos/components/TodosGrid";

export const metadata = {
  title: "Rest Todos",
  description: "Generated by create next app",
};

export default async function RestTodosPage() {
  const todos = await prisma.todo.findMany({ orderBy: { description: "asc" } });

  // useEffect(() => {
  //   fetch("/api/todos")
  //     .then((res) => res.json())
  //     .then((data) => console.log(data));
  // }, []);

  return (
    <div>
      <TodosGrid todos={todos} />
    </div>
  );
}
