import prisma from "@/lib/prisma";

export const metadata = {
  title: "Rest Todos",
  description: "Generated by create next app",
};

export default async function RestTodosPage() {
  const todos = await prisma.todo.findMany({ orderBy: { description: "asc" } });

  // useEffect(() => {
  //   fetch("/api/todos")
  //     .then((res) => res.json())
  //     .then((data) => console.log(data));
  // }, []);

  return (
    <div>
      <h1>Rest Todos Page</h1>
      {
        todos.map((todo) => (
          <div key={todo.id}>
            <h2>{todo.description}</h2>
          </div>
        ))
      }
    </div>
  );
}
